name: doctor_appointment_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  lottie: ^2.0.0
  dio: ^4.0.6
  rating_dialog: ^2.0.4
  shared_preferences: ^2.0.15
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0

cupertino_icons: ^1.0.2

flutter:
  # assets:
  #   - assets/facebook.png
  #   - assets/google.png
  assets:
    - assets/
  uses-material-design: true

